mysite/blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'blog'
urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    #path('', views.PostListViev.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('tag/<slug:tag_slug>/',views.post_list, name='post_list_by_tag'),
    #path('login/', views.user_login, name='login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('dashboard/',views.dashboard,name='dashboard'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls', namespace='blog')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/blog/models.py
from django.db import models

# Create your models here.

from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

class Post(models.Model):
    STATUS_CHOISES=(('draft','Draft'),('published','Published'),)

    title=models.CharField(max_length=250,verbose_name='Post name')
    slug=models.SlugField(max_length=250,unique_for_date='publish')
    author=models.ForeignKey(User,on_delete=models.CASCADE, related_name='blog_posts',verbose_name='Author')
    short_description=models.CharField(max_length=400,verbose_name='Description')
    publish=models.DateTimeField(default=timezone.now,verbose_name='Publish date')
    tags = TaggableManager()
    created = models.DateTimeField(auto_now_add=True, verbose_name='Create date')
    updated = models.DateTimeField(auto_now=True, verbose_name='Update')
    status=models.CharField(max_length=10, choices=STATUS_CHOISES,default='draft')
    image=models.ImageField(upload_to='porodact_images/',verbose_name='Image',blank=False)

    class Meta:
        ordering=('-publish',)
    def __str__(self):
        return self.title
    def get_absolut_url(self):
        return reverse('blog:post_detail',args=[self.publish.year,
                                                self.publish.month,
                                                self.publish.day,
                                                self.slug])

def save_images(instance,filename):
    post_id=instance.post.id
    return 'gallery_images/{}/{}'.format(post_id,filename)

class PostPoint(models.Model):
    post_header=models.CharField(max_length=250,default='HEADER')
    post=models.ForeignKey(Post,on_delete=models.CASCADE,default=None)
    post_point_text=models.TextField(verbose_name='Post point')
    post_images = models.ImageField(upload_to=save_images, verbose_name='Image point', blank=True,)
    def __str__(self):
        return 'Post point {}'.format(self.post.title)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def str(self):
        return 'Комментарий написан {} о {}'.format(self.name, self.post)

mysite/blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email','body')

class LoginForm(forms.Form):
    username=forms.CharField(widget=forms.TextInput(attrs={
        "id":"inputLogin",
        "class":"form-control",
        "placeholder":"Логін",
    }))
    password=forms.CharField(widget=forms.PasswordInput(attrs={
        "type":"password",
        "id":"inputPassword",
        "class":"form-control",
        "placeholder":"Пароль",}))

mysite/blog/views.py
from django.shortcuts import render ,get_object_or_404
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
# Create your views here.
from .models import Post, PostPoint
from django.views.generic import ListView
from .models import Comment
from .forms import CommentForm
from taggit.models import Tag
from django.db.models import Count

from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .forms import LoginForm
from django.contrib.auth.decorators import login_required


@login_required
def dashboard(request):
    user=request.user
    posts_pub=Post.objects.filter(author=user, status='published')
    posts_draft = Post.objects.filter(author=user, status='draft')
    return render(request,'blog/account/dashboard.html',{'post_pub':posts_pub,'post_draft':posts_draft})
def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'blog/account/login.html', {'form': form})
class PostListViev(ListView):
    queryset=Post.objects.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

@login_required
def post_list(request, tag_slug=None):
    object_list = Post.objects.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:

        posts = paginator.page(1)
    except EmptyPage:

        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post/list.html', {'page': page,
                                                   'posts': posts,
                                                   'tag': tag})



def post_detail(request, year, month, day, post):
    post_object = get_object_or_404(Post, slug=post, status='published',
                                    publish__year=year,
                                    publish__month=month,
                                    publish__day=day)
    post_points = PostPoint.objects.filter(post=post_object)

    comments = post_object.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':

        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            cd = comment_form.cleaned_data
            new_comment = Comment(post=post_object, name=cd['name'], email=cd['email'], body=cd['body'])
            new_comment.save()
    else:
        comment_form = CommentForm()

    post_tags_ids = post_object.tags.values_list('id', flat=True)
    similar_posts = Post.objects.filter(tags__in=post_tags_ids, status='published').exclude(id=post_object.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(request, 'blog/post/detail.html', {'post': post_object,
                                                     'post_points': post_points,
                                                     'comments': comments,
                                                     'new_comment': new_comment,
                                                     'comment_form': comment_form,
                                                     'similar_posts': similar_posts
                                                     })

mysite/blog/templates/blog/account/dashboard.html
{% extends "blog/base.html" %}
{% block title %}Oсобистий кабінет{% endblock %}
{% block content %}
    <h1>Oсобистий кабінет</h1>

    {% if posts_pub %}
        <h2>Мої опубліковані статті: </h2>
        {% for post in posts_pub %}
            <h3><a href="{{post.get_absolute_url}}">{{ post.title }}</a></h3>
        {% endfor %}
    {% endif %}
    {% if posts_draft %}
        <h2>Мої не опубліковані статті:</h2>
        {% for post in posts_draft %}
            <h3>{{ post.title }}</h3>
            <p>{{ post.short_descriptions }}</p>
        {% endfor %}

    {% endif %}


{% endblock %}

mysite/blog/templates/blog/account/login.html
{% extends "blog/base.html" %}
{% block title %}
    Логін
{% endblock title %}

{% block content %}
    <div class="container text-center sign-in">
        <form action="." class="form-sign-in login-form" method="post">
       <h1 class="h3 mb-3 font-weight-normal">Будь ласка авторизуйтесь</h1>
        <label for="inputLogin" >Логін</label>
            {{ form.username }}
        <label for="inputPassword" >Пароль</label>
            {{ form.password }}
            {% csrf_token %}
            <button class="btn btn-lg btn-primary mt-2" type="submit">
                Увійти
            </button>
        </form>
    </div>
{% endblock content %}

mysite/blog/templates/blog/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="UTF-8">
   <title>{%block title%} {% endblock %}</title>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
   <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>

   
   {% block navbar %}
     <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
         <a class="navbar-brand" href="{% url 'blog:post_list' %}">Головна</a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
         </button>

         <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">

             <form class="form-inline my-2 my-lg-0">
                 <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                 <button class="btn btn-dark my-2 my-sm-0" type="submit">Search</button>
             </form>
         </div>
             <div id="header">
                <span class="user">
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'blog:dashboard' %}" class="pr-3">
                            {{ request.user.first_name }}
                        </a>
                        <a href="{% url 'blog:logout' %}">Вийти</a>
                    {% else %}
                        <a href="{% url 'blog:login' %}">Увійти</a>
                    {% endif %}
                </span>
            </div>
     </nav>
   {% endblock %}

   {%block content%}
     <h1>Content</h1>
   {% endblock %}




<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

</body>

</html>

mysite/blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% block title %}
    {{ post.title }}
{% endblock %}
{% block content %}


    <div class="container my-3">
        <div class="card-deck">
            <div class="card">
                <img src="{{ MEDIA_URL }}{{ post.image.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">{{ post.short_description }}</p>
                </div>
                {% for post_point in post_points %}
                    <div class="card-body">
                        <h5 class="card-title">{{ post_point.post_point_header}}</h5>
                        {% if post_point.post_image %}
                            <img src="{{ MEDIA_URL }}{{ post_point.post_image.url }}" class="card-img-top" alt="..."
                            style="width: 500px">
                        {% endif %}
                        {% if post_point.post_point_header == "Ингредиенты" %}
                            <pre class="card-text">{{ post_point.post_point_text }}</pre>
                        {% else %}
                            <p class="card-text">{{ post_point.post_point_text }}</p>
                        {% endif %}

                    </div>
                {% endfor %}
                <div class="card-footer">
                    <small class="text-muted">Опубликовано {{ post.publish }}. Автор {{ post.author }}</small>
                </div>
            </div>

        </div>
    </div>

{% with comments.count as total_comments  %}
    <h2> Коментарів : {{ total_comments }}</h2>
{% endwith %}

{% for comment in comments %}
        <div class="card border-dark mb-3" >
          <div class="card-header"><b>{{ forloop.counter }}. </b> {{ comment.name }},  E-mail {{ comment.email }}</div>
           <div class="card-body  text-dark">
            <p class="card-text">{{ comment.body }}</p>
          </div>
        </div>
{% endfor %}

<div class="m-5">
                    {% if new_comment %}
                        <h2>Ваш комментарий добавлен</h2>
                    {% else %}
                        <h2>Добавить комментарий</h2>
                        <form action="." method="post">
                        <div class="form-group">
                            <label for="nameInput">Имя</label>
                            {{ comment_form.name }}
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Ваш Email </label>
                            {{ comment_form.email }}
                        </div>
                        <div class="form-group">
                            <label for="comment">Коментар</label>
                            {{ comment_form.body }}
                        </div>
                            <button type="submit" class="btn btn-outline-info">Додати</button>
                        {% csrf_token %}
                        </form>
                    {% endif %}
                </div>
<h2> Similar posts </h2>
{% for post in similar_posts %}
    <p>
      <a href="{{ post.get_absolut_url }}">{{ post.title }}</a>
    </p>
{% empty %}
    There are no similar posts yet.
{% endfor %}
{% endblock %}

mysite/blog/templates/blog/post/list.html
{%extends 'blog/base.html'%}
{%block title%} My blog {%endblock%}
{%block content%}
    <h1 class="title text-center my-3">Кулінарна книга</h1>
    <div class="container">
        <div class="card-deck">
            <div class="container">
                {% if tag %}
                    <h2 class="text-center"> Теги:  "{{ tag.name }}"</h2>
                {% endif %}

             <div class="card-deck">

            {% for post in posts %}
                <div class="card">
                    <a href="{{ post.get_absolut_url }}">
                        <img src="{{ MEDIA_URL }}{{ post.image.url }}" class="card-img-top" alt="...">
                    </a>
                    <div class="card-body">
                        <a href="{{ post.get_absolut_url }}">
                            <h5 class="card-title">{{ post.title }}</h5>
                        </a>
                        <p class="card-text">{{ post.short_description }}</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">Опубликовано {{ post.publish }}. Автор {{ post.author }}</small>
                        <p>Tags:
                            {% for tag in post.tags.all %}
                                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                                {{ tag.name }}
                                </a>
                                {% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </p>
                </div>
            {% endfor %}
        </div>
    </div>

{% include 'paginations.html' with page=posts %}
{%endblock%}

mysite/blog/templates/paginations.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{page.previous_page_number}}"> < Попередня </a>
        {% endif %}
        <span class="current">
            Cторінка {{ page.number }} з {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}"> Наступна > </a>
        {% endif %}
    </span>
</div>